import { useFormik } from 'formik';
import Head from 'next/head'
import {api} from "../api/config"

export default function Home() {
  

  const validate = values => {
    const errors = {};
    if (!values.title) {
      errors.title = 'Required';
    } else if (values.title.length < 5) {
      errors.title = 'Must be 5 characters or more';
    }
  
    if (!values.body) {
      errors.body = 'Required';
    } else if (values.body.length < 20) {
      errors.body = 'Must be 20 characters or more';
    }

    return errors;
  };

  const formik = useFormik({
    initialValues: {
      title: '',
      group: "",
      body: ""
    },
    validate,
    onSubmit: values => {
      values.group=values.group.replace(/\s/g, "");
      alert(JSON.stringify(values, null, 2));
      api.post('/topic/send',values).then(res=>{
        alert(res.data)
      }).catch(err=>{
        alert(err)
      })
    },
  });

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container h-screen mx-auto px-4'>
        <div className='py-6'>
          <p className='text-4xl font-semibold'>Send Notification</p>
        </div>
        <form onSubmit={formik.handleSubmit}>
          <label className="block mt-6">
            <span className="text-gray-700">Title</span>
            <input className="form-input mt-1 block w-2/5 border-2  rounded" placeholder="Notification Title" id="title" name="title" onChange={formik.handleChange}
              value={formik.values.title} 
              onBlur={formik.handleBlur}
              />
              {formik.touched.title && formik.errors.title ? (
                <p className='text-md text-red-600'>{formik.errors.title}</p>
              ) : null}
        
          </label>

          <label className="block mt-8">
            <span className="text-gray-700">Group</span>
            <select className="form-select mt-1 block w-2/5 border-2 rounded"
              onChange={formik.handleChange}
              value={formik.values.group}
              onBlur={formik.handleBlur}
              name="group"
              id="group"
            >
              <option>group A</option>
              <option>group B</option>
              <option>group C</option>
            </select>
          </label>

          <label className='block mt-10'>
            <span className='text-gray-700'>
              Body
            </span>
            <textarea className="form-input mt-1 block w-full h-3/4 border-2  rounded" placeholder="Message here..." onChange={formik.handleChange}
              value={formik.values.body}
              name="body"
              id="body"
              onBlur={formik.handleBlur}
            />
            {formik.touched.body && formik.errors.body ? <p className='text-md text-red-600'>{formik.errors.body}</p> : null}
          </label>
          <div className='mt-4 px-2 '>
            <button type="submit" className='border-2 rounded bg-blue-400 w-24 hover:bg-blue-300'>
              <p className=' text-lg font-medium'>Send</p>
            </button>
          </div>
        </form>




      </main>

      <footer >

      </footer>
    </div>
  )
}
